general {
    hide_cursor = true
    immediate_render = true
}
animations {
    enabled = false
}
background {
    monitor =
    color = rgb(1a1b26)
}
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    rounding = 0
    outer_color = rgb(9fe3c4)
    inner_color = rgb(1a1b26)
    font_color = rgb(bbbbbb)
    placeholder_text = Password
}
