Section "InputClass"
    Identifier "x11 touchpads"
    MatchIsTouchpad "on"
    MatchDriver "libinput"
    Option "NaturalScrolling" "true"
    Option "Tapping" "true"
    Option "DisableWhileTyping" "true"
EndSection

Section "InputClass"
    Identifier "x11 mice (not pointing sticks)"
    MatchIsPointer "on"
    MatchIsTouchpad "off"
    MatchDriver "libinput"
    MatchTag "x11-mouse"
    Option "NaturalScrolling" "true"
EndSection

Section "InputClass"
    Identifier "x11 US keyboard"
    MatchIsKeyboard "on"
    Option "XkbLayout" "us"
EndSection
